server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: 49.234.36.144:8080
       server-addr: localhost:8848  #配置nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
